services:
  cloudinary-profiler-v3:
    build: .
    volumes:
      - ./profiler_output:/tmp/xdebug
      - ./src:/app/src
    environment:
      - XDEBUG_MODE=profile
    platform: linux/amd64  # Ensures compatibility with Mac M1
    stdin_open: true
    tty: true